### ISSUE TITLE
AttributeError: module 'keras.api._v2.keras.mixed_precision' has no attribute 'experimental'

### ISSUE THREAD

**Issue by prajvalmohan23** [jamesdolezal/slideflow#167]
**Bug/Issue:**
When a model is run (eg. `python exp_uchsinus_models.py `), the following error pops up:
```
Process SpawnProcess-4:
Traceback (most recent call last):
  File "/home/prajval/anaconda3/envs/sf/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/prajval/anaconda3/envs/sf/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/prajval/slideflow/slideflow/project_utils.py", line 108, in _train_worker
    trainer = sf.model.trainer_from_hp(**model_kw)
  File "/home/prajval/slideflow/slideflow/model/__init__.py", line 73, in trainer_from_hp
    return Trainer(hp=hp, **kwargs)
  File "/home/prajval/slideflow/slideflow/model/tensorflow.py", line 1045, in __init__
    policy = tf.keras.mixed_precision.experimental.Policy(policy_str)
AttributeError: module 'keras.api._v2.keras.mixed_precision' has no attribute 'experimental'
```
I think this arises due to the difference in TensorFlow commands in various versions:

**Suggested fix:**
_Current code:_ "./slideflow/slideflow/model/tensorflow.py" - line 1045 and 1046
```
policy = tf.keras.mixed_precision.experimental.Policy(policy_str)
tf.keras.mixed_precision.experimental.set_policy(policy)
```
_Change to:_ 
```
tf.keras.mixed_precision.set_global_policy(policy_str)
```

**Comment by jamesdolezal** [comment]
Thanks! I added some logic to do version comparisons, since I'm not sure the new syntax will work with older versions of Tensorflow. 

Let me know if any new issues come up with TF 2.9 - I haven't had a chance to test 2.9 yet.
