### ISSUE TITLE
Tutorial 4: Model evaluation & heatmaps, Asking for ROIs

### ISSUE THREAD

**Issue by juanenofbit** [jamesdolezal/slideflow#202]
I am tryning to replicate the tutorial 4 "Model Evaluation & heatmaps"
https://slideflow.dev/tutorial4.html, using a model trained according to the first part of the tutorial.

But in the calculation of the heatmaps an error appears because it needs ROIs, although in the tutorial the step of how to create them is not described. No heatmaps are written to disk.

```
model   = '/home/juan/histopathology_data/slideflow/project_brca/models/00000-er_status_by_ihc-HP0-kfold1/er_status_by_ihc-HP0-kfold1_epoch10'
project = '/home/juan/histopathology_data/slideflow/project_brca'

P = sf.Project(project)
P_heat = P.generate_heatmaps(
        model,
        filters={'dataset': ['eval']},
        resolution='high' # options include "low", "medium" and "high"
    )
```

The following error messages appear for each slide:

```
19:30:26] INFO     Generating heatmaps for 190 slides.                                                            

           INFO     Model:                                                                                         
                    /home/juan/histopathology_data/slideflow/project_brca/models/00000-er_status_by_ihc-HP0-kfold1/
                    er_status_by_ihc-HP0-kfold1_epoch10                                                            

           INFO     Tile px: 299                                                                                   

           INFO     Tile um: 145                                                                                   

[19:30:38] WARNING  No ROIs provided for                                        
                    TCGA-UU-A93S-01Z-00-DX1.C4809779-DF5F-4F5D-A78C-B7F95F2D050F

Process SpawnProcess-191:
Traceback (most recent call last):
  File "/home/juan/anaconda3/envs/slideflow/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/home/juan/anaconda3/envs/slideflow/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/juan/anaconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/project_utils.py", line 93, in _heatmap_worker
    heatmap = sf.Heatmap(slide,
  File "/home/juan/anaconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/heatmap.py", line 145, in __init__
    self.slide = WSI(
  File "/home/juan/anaconda3/envs/slideflow/lib/python3.9/site-packages/slideflow/slide/__init__.py", line 1515, in __init__
    raise errors.MissingROIError(
slideflow.errors.MissingROIError: Slide [green]TCGA-UU-A93S-01Z-00-DX1.C4809779-DF5F-4F5D-A78C-B7F95F2D050F[/] missing ROI.

```

**Comment by jamesdolezal** [comment]
Thank you for raising this issue! The default value for the `roi_method` argument for the `generate_heatmaps()` function got changed from `'auto'` (using ROIs if available) to `'inside'` (expects an ROI and raises an error if misssing) somewhere along the way. I've changed the default value back to 'auto'. This update will be included in version 1.4.

In the meantime, you can avoid the error by passing the argument `roi_method='auto'`:

```python
P.generate_heatmaps(..., roi_method='auto')
```
