### ISSUE TITLE
setting up PyTorch plugin "bias_act_plugin"... Failed

### ISSUE THREAD

**Issue by Meijian** [jamesdolezal/slideflow#255]
## Description

When running stylegan3, it complains about setting up PyTorch plugin "bias_act_plugin"... Failed. Not sure if it's a system thing because I saw others running gan having similar issues online. Just post it here to see if you guys have any comments or solutions for this.

## To Reproduce
P.gan_train(
  dataset=dataset,
  model='stylegan3',
  cfg='stylegan3-r',
  exp_label="kmeans",
  gpus=4,
  batch=32
)

setting up PyTorch plugin "bias_act_plugin"... Failed!
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/databricks/python/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/gan/stylegan3/stylegan3/train.py", line 58, in subprocess_fn
    training_loop.training_loop(rank=rank, **c)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/gan/stylegan3/stylegan3/training/training_loop.py", line 195, in training_loop
    img = misc.print_module_summary(G, [z, c])
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/gan/stylegan3/stylegan3/torch_utils/misc.py", line 227, in print_module_summary
    outputs = module(*inputs)
  File "/databricks/python/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/gan/stylegan3/stylegan3/training/networks_stylegan3.py", line 513, in forward
    ws = self.mapping(z, c, truncation_psi=truncation_psi, truncation_cutoff=truncation_cutoff, update_emas=update_emas)
  File "/databricks/python/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/gan/stylegan3/stylegan3/training/networks_stylegan3.py", line 153, in forward
    x = getattr(self, f'fc{idx}')(x)
  File "/databricks/python/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1212, in _call_impl
    result = forward_call(*input, **kwargs)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/gan/stylegan3/stylegan3/training/networks_stylegan3.py", line 102, in forward
    x = bias_act.bias_act(x, b, act=self.activation)
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/gan/stylegan3/stylegan3/torch_utils/ops/bias_act.py", line 101, in bias_act
    if impl == 'cuda' and x.device.type == 'cuda' and _init():
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/gan/stylegan3/stylegan3/torch_utils/ops/bias_act.py", line 58, in _init
    _plugin = custom_ops.get_plugin(
  File "/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.9/site-packages/slideflow/gan/stylegan3/stylegan3/torch_utils/custom_ops.py", line 136, in get_plugin
    torch.utils.cpp_extension.load(name=module_name, build_directory=cached_build_dir,
  File "/databricks/python/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1284, in load
    return _jit_compile(
  File "/databricks/python/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1508, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/databricks/python/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1623, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/databricks/python/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1916, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'bias_act_plugin': [1/3] c++ -MMD -MF bias_act.o.d -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /databricks/python/lib/python3.9/site-packages/torch/include -isystem /databricks/python/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /databricks/python/lib/python3.9/site-packages/torch/include/TH -isystem /databricks/python/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /root/.cache/torch_extensions/py39_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-tesla-t4/bias_act.cpp -o bias_act.o 
FAILED: bias_act.o 
c++ -MMD -MF bias_act.o.d -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /databricks/python/lib/python3.9/site-packages/torch/include -isystem /databricks/python/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /databricks/python/lib/python3.9/site-packages/torch/include/TH -isystem /databricks/python/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /root/.cache/torch_extensions/py39_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-tesla-t4/bias_act.cpp -o bias_act.o 
In file included from /root/.cache/torch_extensions/py39_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-tesla-t4/bias_act.cpp:10:
/databricks/python/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:6:10: fatal error: cusparse.h: No such file or directory
    6 | #include <cusparse.h>
      |          ^~~~~~~~~~~~
compilation terminated.
[2/3] /usr/local/cuda/bin/nvcc  -DTORCH_EXTENSION_NAME=bias_act_plugin -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /databricks/python/lib/python3.9/site-packages/torch/include -isystem /databricks/python/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /databricks/python/lib/python3.9/site-packages/torch/include/TH -isystem /databricks/python/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_75,code=compute_75 -gencode=arch=compute_75,code=sm_75 --compiler-options '-fPIC' --use_fast_math --allow-unsupported-compiler -std=c++14 -c /root/.cache/torch_extensions/py39_cu117/bias_act_plugin/3cb576a0039689487cfba59279dd6d46-tesla-t4/bias_act.cu -o bias_act.cuda.o 
ninja: build stopped: subcommand failed.

## Environment:

 - Slideflow Version (e.g., 1.0): 2.0.2
 - OS (e.g., Ubuntu): Ubuntu on Databricks
 - How you installed Slideflow (`pip`, source): pip
 - Python version: 3.9
 - CUDA/cuDNN version:
 - GPU models and configuration: T4
 - Any other relevant information:

**Comment by jamesdolezal** [comment]
Yes, this is an issue with compiling the custom CUDA modules that StyleGAN loads. Although it's not an issue on our end, we can try some troubleshooting to help future users who may encounter a similar issue. What version of CUDA and PyTorch do you have installed?

**Comment by Meijian** [comment]
Sure, that would be great! Thanks. Versions below.
CUDA: 11.4
torch: 1.13.1+cu117

**Comment by jamesdolezal** [comment]
StyleGAN [requires PyTorch <0.12](https://slideflow.dev/installation/). StyleGAN3 runs best with version 1.10 or 1.11 - version 1.12 runs a bit slower, for some reason. StyleGAN2 needs PyTorch 1.9.

**Comment by jamesdolezal** [comment]
This is an issue with the StyleGAN3 module as implemented by NVIDIA. There are a couple of threads discussing the issue, as the solution may depend on your environment:

https://github.com/NVlabs/stylegan3/issues/124

In your error message, the line `/databricks/python/lib/python3.9/site-packages/torch/include/ATen/cuda/CUDAContext.h:6:10: fatal error: cusparse.h: No such file or directory` makes the think that the issue is related to how CUDA is installed, or how CUDA is communicating with the stylegan3 modules that need to be compiled.

Unfortunately this isn't something I can directly solve or troubleshoot. I would recommend looking for a solution in the StyleGAN3 repository, or trying some of the solutions in the link above.

**Comment by jamesdolezal** [comment]
I'll keep the issue open until a solution is found, in case others have the same problem.

**Comment by jamesdolezal** [comment]
Going to close this issue due to inactivity. But in case anyone stumbles across this in the future and is looking for troubleshooting steps, here's some things you can try.

First, enable verbose debug logging in the StyleGAN submodule, which will give you more detailed information in the terminal. You can do this by first locating the `custom_ops.py` file within slideflow (`slideflow/gan/stylegan2/stylegan2/torch_utils/custom_ops.py`, or replace stylegan2 with stylegan3 as needed). Then change the following line:

```
verbosity = 'brief' # Verbosity level: 'none', 'brief', 'full'
```
to
```
verbosity = 'full' # Verbosity level: 'none', 'brief', 'full'
```
Now, when you attempt to train stylegan and get to the `"bias_act_plugin"...` step, you should see more messages in your terminal output.

StyleGAN builds custom PyTorch extensions, which are stored in a temporary cache directory. Sometimes, the files created and stored in this temporary folder can become corrupt, and clearing out the cache can fix StyleGAN training issues.

With verbose debug logging enabled, one of the terminal messages you may see should include something like:

```
Using /mnt/data/home/[username]/.cache/torch_extensions/py39_cu113 as PyTorch extensions root..
```

Try deleting this folder and re-running training. In many cases, this will fix the problem.

Meijian - I hope you were able to resolve the issue. Let me know if not and we can re-open.

**Comment by andrewsris** [comment]
Hi James,

I just wanted to relay my investigations so far. I am closer, but still do not have a working environment. The above strategy did not work in my environment:
Slideflow 2.0.3+92.g1c4aa6d5.dirty
Python 3.8.10
Torch Version: 1.10.1+cu111 
Cuda 11.2

The first issues is that I was missing three files called cusparse.h,  cublas_v2.h, and cusolverDn.h. Others have noted that this is in the dev package (https://github.com/facebookresearch/maskrcnn-benchmark/issues/685#issuecomment-596144324), which is not automatically installed with cuda. Installing the version of dev packages seems to get rid of the "missing file" errors.

On an environment with sudo privileges, I ran (for cuda v11.2)
`apt-get install libcusparse-dev-11-2
apt-get install libcublas-dev-11-2
apt-get install libcusolver-dev-11-2
`
However, I am still not able to train correctly because now I just the error that all CUDA devices are busy, which they aren't. I confirmed that torch can see the CUDA devices, as  I can still train a model with tile-based methods on 4 GPUs using the tensorflow backend and torch backend. I am not sure where to go from here.


Note for those on HPC's, this is challenging to do on an HPC without sudo privileges (https://github.com/apptainer/singularity/issues/5903#issuecomment-821976992). My solution was to download the slideflow docker/singularity container on a personal PC with sudo privileges. Then I was able to create a writable overlay (with at least 1000MB of space) on top the image and install the above development packages. Afterwards, I was able to transfer the overlay.img file to an HPC and change the permissions of the overlay.img to allow non-root to execute it (chmod 777). Then you should be able to run the singularity container with the overlay and see that your newly installed packages are included.
