### ISSUE TITLE
MemoryError and SystemError

### ISSUE THREAD

**Issue by p024eb** [jamesdolezal/slideflow#261]
## Description
I generated features with DatasetFeatures() function for MIL. The number of tiles in TFRecords is over 10 million.
The following error occurred:
> Number of tiles in TFRecords: 12825545
Annotation columns:
Index(['Unnamed: 0', 'slide', 'patient', 'grade', 'category'], dtype='object')
[01:57:18] INFO     Calculating activations for 1247 tfrecords (layers=['postconv'])
           INFO     Generating from <TorchImagenetLayerExtractor model=resnet50 layers=['postconv'] n_features=2048>
SystemError: deallocated bytearray object has exported buffers
Exception in thread Thread-130:
Traceback (most recent call last):
  File "/home/ochi/anaconda3/envs/slideflow2/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/home/ochi/anaconda3/envs/slideflow2/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ochi/anaconda3/envs/slideflow2/lib/python3.8/site-packages/slideflow/io/torch.py", line 1021, in interleaver
    record = next(sampler_iter)
  File "/home/ochi/anaconda3/envs/slideflow2/lib/python3.8/site-packages/slideflow/tfrecord/iterator_utils.py", line 56, in __iter__
    yield next(iterators[choice])
  File "/home/ochi/anaconda3/envs/slideflow2/lib/python3.8/site-packages/slideflow/tfrecord/reader.py", line 149, in __iter__
    yield from read_records(start_byte, end_byte)
  File "/home/ochi/anaconda3/envs/slideflow2/lib/python3.8/site-packages/slideflow/tfrecord/reader.py", line 103, in read_records
    self.datum_bytes = self.datum_bytes.zfill(_fill)
MemoryError
SystemError: deallocated bytearray object has exported buffers

## To Reproduce
Codes to  reproduce the behavior:
`features = sf.DatasetFeatures(resnet50, dataset)`
`features.to_torch('/bag/')`

## Environment:
- Slideflow Version (e.g., 1.0): 2.0.3
- OS (e.g., Ubuntu): Ubuntu
- How you installed Slideflow (pip, source): pip
- Python version: 3.8
- CUDA/cuDNN version:
- GPU models and configuration:
- Any other relevant information:

**Comment by jamesdolezal** [comment]
It sounds like your system ran out of memory when attempting to generate these features. 

The DatasetFeatures interface keeps image features for all tiles in memory before exporting. If you have a lot of image tiles (10 million), this is likely to exceed your system memory.

If you're generating features for MIL, a better solution would be to save features to disk as they are being calculated, instead of keeping this data in memory. This would eliminate the problem of excessive memory usage, but would prevent users from doing other downstream tasks that require all data to be in memory (like UMAPs, mosaic maps, etc). 

We are planning to add a function in version 2.1 that allows users to generate features and save them to disk as they are being calculated, for downstream MIL, to reduce memory consumption. But it's not ready quite yet.

In the meantime, you can get around the high memory utilization by splitting the full dataset into many smaller parts, and calculating/exporting features for each part separately.

For example:

```
import slideflow as sf

slides = dataset.slides()
for batch in sf.util.batch(slides, 8):
    ftrs = sf.DatasetFeatures(..., dataset.filter({"slide": batch}))
    ftrs.to_torch(...)

```

This would calculate and explore features 8 slides at a time.

I'll keep this issue open and update it when we have the permanent solution for 2.1.

**Comment by p024eb** [comment]
Your example codes enabled us to deal with entire tiles in all TFrecords without any errors, but I am waiting for releasing version 2.1
Thank you!
